# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62c24270ecb8529b2e933cfb63e1e8334e6f255e79dbeb2aa5e902823a77a95176f7468af1b81521ae2a30911f171a67eb55563dafe863533afd21b03b0a740a

test:
  secret_key_base: a71c7938c4bbd37fd4b45f0415090577fafb24db2928053defb186532091d3804a227adbf2918ecd4496532f243a436aecb292f594331816dd67c435060f8233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
